FROM opensuse:42.2
RUN zypper --non-interactive install openssh openSUSE-release

# create host ssh key
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''

# install public key for root
RUN mkdir -p /root/.ssh
#__INSERTPUBLICKEY__
RUN chmod -R 600 /root/.ssh

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
#CMD ["/bin/bash"]
